apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    app: elasticsearch
  name: elasticstorage
  selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate