apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging 
  labels:
    app: kibana 
spec:
  selector:
    app: kibana 
  ports:
  - port: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.4.3
        env:
          - name: ELASTICSEARCH_URL 
            value: http://elasticsearch:9200
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 5601 
