# define service first 
apiVersion: v1
kind: Service
metadata:
  name: product 
spec:
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product 
spec:
  selector:
    matchLabels:
      app: product 
  template:
    metadata:
      labels:
        app: product 
    spec:
      containers:
      - name: product 
        image: rockink/product
        env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "-Xms200m -Xmx200m"
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

